import 'package:flutter/material.dart';

class AppCore {
  static const LinearGradient defaultOrangeGradient = LinearGradient(
    colors: [
      Color(0xFFFD620D),
      Color(0xffFF7B01),
      Color(0xffFF8F27),
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );

  static LinearGradient getOrangeGradient() {
    return defaultOrangeGradient;
  }

  static const List<String> categoriasMock = [
    'Aperitivos e petiscos',
    'Pratos principais',
    'Sobremesas',
    'Saladas',
    'Sopas e caldos',
    'Massas e risotos',
    'Bolos e tortas',
    'Bebidas',
    'Sanduíches e wraps',
    'Café da manhã e brunch',
    'Lanches e snacks',
    'Pratos vegetarianos e veganos',
    'Pratos sem glúten',
    'Pratos sem lactose',
    'Pratos regionais',
    'Churrasco e grelhados',
    'Receitas para crianças',
    'Receitas saudáveis',
    'Comida rápida e prática',
    'Pratos internacionais',
    'Molhos e acompanhamentos',
    'Receitas de peixe e frutos do mar',
    'Receitas de carne',
    'Receitas de aves',
    'Receitas de sopas e ensopados',
    'Receitas de doces e confeitaria',
    'Receitas de pães e massas caseiras'
        'selecione uma categoria'
  ];

  static const List<String> unidades = [
    'Unidade',
    'Fatia',
    'Copo',
    'Pitada',
    'Porção',
    'Taça',
    'Tablete',
    'Lata',
    'Rodela',
    'Colher de sopa cheia',
    'Colher de sopa rasa',
    'Colher de sobremesa',
    'Colher de chá rasa',
    'Xícara de café',
    'Xícara de chá',
    'Garrafa ',
    'Bandeja',
    'Sache',
    'Folha',
    'Filé',
    'Punhado',
    'Pedaço',
    'Pacote',
    'Envelope',
    'Litro',
    'Mililitro',
    'Copo Americano',
    'Gramas',
    'Quilogramas',
    'selecione uma medida'
  ];

  static const List<String> ingredientesMock = [
    'Maçã',
    'Banana',
    'Laranja',
    'Uva',
    'Morango',
    'Abacaxi',
    'Melancia',
    'Mamão',
    'Manga',
    'Kiwi',
    'Pêssego',
    'Ameixa',
    'Pera',
    'Limão',
    'Maracujá',
    'Cereja',
    'Framboesa',
    'Mirtilo',
    'Goiaba',
    'Carambola',
    'Melão',
    'Pitaya',
    'Tangerina',
    'Nectarina',
    'Caqui',
    'Cenoura',
    'Batata',
    'Tomate',
    'Abóbora',
    'Pepino',
    'Berinjela',
    'Pimentão',
    'Cebola',
    'Alho-poró',
    'Alface',
    'Espinafre',
    'Brócolis',
    'Couve-flor',
    'Repolho',
    'Ervilha',
    'Milho',
    'Vagem',
    'Quiabo',
    'Chuchu',
    'Rabanete',
    'Beterraba',
    'Nabo',
    'Aipo (salsão)',
    'Rúcula',
    'Alcachofra',
    'Alface',
    'Espinafre',
    'Rúcula',
    'Agrião',
    'Acelga',
    'Endívia',
    'Almeirão',
    'Couve',
    'Mostarda',
    'Escarola',
    'Chicória',
    'Salsa',
    'Coentro',
    'Hortelã',
    'Manjericão',
    'Tomilho',
    'Alecrim',
    'Cebolinha',
    'Pimenta-de-cheiro',
    'Pimenta-dedo-de-moça',
    'Pimentão',
    'Quiabo',
    'Jiló',
    'Maxixe',
    'Taioba',
    'Alcatra',
    'Picanha',
    'Maminha',
    'Fraldinha',
    'Cupim',
    'Filé mignon',
    'Contrafilé',
    'Costela',
    'Rabo',
    'Acém',
    'Paleta',
    'Lagarto',
    'Peito',
    'Linguiça de carne bovina',
    'Miolo de alcatra',
    'Capa de filé',
    'Pontinha de agulha',
    'Coxão duro',
    'Coxão mole',
    'Patinho',
    'Cabeça de lombo',
    'Filé de costela',
    'Fígado bovino',
    'Coração bovino',
    'Rins bovinos',
    'selecione um ingrediente'
  ];

  void successDialog(BuildContext context, String textSuccess) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text('Sucesso'),
          content: Text(textSuccess),
          actions: <Widget>[
            TextButton(
              onPressed: () {
                Navigator.of(context).pop();
              },
              child: const Text('OK'),
            ),
          ],
        );
      },
    );
  }
}
